"""phase6a_chairs

Revision ID: 1f51f0224943
Revises: 507ef4c2d805
Create Date: 2026-07-08 11:45:41.444101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f51f0224943'
down_revision: Union[str, Sequence[str], None] = '507ef4c2d805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chairs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role_title', sa.String(length=255), nullable=False),
    sa.Column('areas', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chairs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chairs_active'), ['active'], unique=False)

    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_chair_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_emails_assigned_chair_id'), ['assigned_chair_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_emails_assigned_chair_id_chairs',
            'chairs', ['assigned_chair_id'], ['id'], ondelete='SET NULL',
        )

    # ### end Alembic commands ###

    # --- Seed the five standing chairs (Phase 6A) ------------------------
    # Reference data, not synthetic test data — seeded in the migration so any
    # environment (dev / CI / container) has a routable chair roster right after
    # `alembic upgrade head`. ``areas`` lists the intent/topic strings each chair
    # owns; the General Chair carries an empty ``areas`` and acts as the catch-all
    # fallback for anything no other active chair claims.
    chairs_table = sa.table(
        "chairs",
        sa.column("name", sa.String),
        sa.column("role_title", sa.String),
        sa.column("areas", sa.JSON),
        sa.column("active", sa.Boolean),
    )
    op.bulk_insert(
        chairs_table,
        [
            {
                "name": "Program Chair",
                "role_title": "Program Chair",
                "areas": [
                    "submission_deadline",
                    "formatting_requirements",
                    "submission_withdrawal",
                    "review_assignment",
                    "technical_issue",
                ],
                "active": True,
            },
            {
                "name": "Diversity & Ethics Chair",
                "role_title": "Diversity & Ethics Chair",
                "areas": ["ethics_concern", "authorship_dispute"],
                "active": True,
            },
            {
                "name": "Local Arrangements Chair",
                "role_title": "Local Arrangements Chair",
                "areas": ["general_inquiry"],
                "active": True,
            },
            {
                "name": "Publicity/Sponsorship Chair",
                "role_title": "Publicity & Sponsorship Chair",
                "areas": ["sponsorship", "publicity", "media_inquiry"],
                "active": True,
            },
            {
                # Empty areas → the catch-all fallback for unmatched intents.
                "name": "General Chair",
                "role_title": "General Chair",
                "areas": [],
                "active": True,
            },
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_constraint('fk_emails_assigned_chair_id_chairs', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_emails_assigned_chair_id'))
        batch_op.drop_column('assigned_chair_id')

    with op.batch_alter_table('chairs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chairs_active'))

    op.drop_table('chairs')
    # ### end Alembic commands ###
