"""initial_schema

Revision ID: 988d40d1a9ee
Revises: 
Create Date: 2026-06-25 11:44:39.599072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '988d40d1a9ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender', sa.String(length=320), nullable=False),
    sa.Column('sender_name', sa.String(length=320), nullable=True),
    sa.Column('subject', sa.String(length=998), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('classification', sa.JSON(), nullable=True),
    sa.Column('routing', sa.JSON(), nullable=True),
    sa.Column('draft', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emails_sender'), ['sender'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_status'), ['status'], unique=False)

    op.create_table('policy_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('policy_key', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_documents_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_documents_policy_key'), ['policy_key'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_email_id'), ['email_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_email_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('policy_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_documents_policy_key'))
        batch_op.drop_index(batch_op.f('ix_policy_documents_category'))

    op.drop_table('policy_documents')
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emails_status'))
        batch_op.drop_index(batch_op.f('ix_emails_sender'))

    op.drop_table('emails')
    # ### end Alembic commands ###
